## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.warn = ignore_warn #ignore annoying warning (from sklearn and seaborn)

In [2]:
# 讀取wine資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)

print(f'Train:{x_train.shape},{y_train.shape}')
print(f'Test:{x_test.shape},{y_test.shape}')

Train:(160, 13),(160,)
Test:(18, 13),(18,)


In [3]:
y_test

array([2, 2, 0, 0, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1])

In [4]:
# 建立模型
logreg = linear_model.LogisticRegression()

# 訓練模型
logreg.fit(x_train, y_train)

# 預測測試集
y_pred = logreg.predict(x_test)

In [5]:
y_pred

array([2, 2, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1])

In [6]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.9444444444444444


In [7]:
# 讀取boston資料集
boston = datasets.load_boston()

scaler = StandardScaler()
data = scaler.fit_transform(boston.data)
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(data, boston.target, test_size=0.1, random_state=4)

print(f'Train:{x_train.shape},{y_train.shape}')
print(f'Test:{x_test.shape},{y_test.shape}')

Train:(455, 13),(455,)
Test:(51, 13),(51,)


In [8]:
y_test

array([16.5, 24.8, 17.4, 19.3, 37.6, 24.2, 35.4, 19.9, 27.5, 17. , 31.2,
       24.4, 16.1, 27. , 21. , 14.9, 18.9,  6.3, 16.3, 13.9,  8.8, 19.4,
       18.8, 19.8, 17.5, 19.3, 20. , 14.3, 16.1, 19.5, 11. , 21.9, 31. ,
       22. , 15.1, 13.3, 28.7, 46.7, 22.2, 22.8, 42.3, 41.3, 16.7, 31.1,
       26.7, 19.4, 50. , 16.6, 19.5, 24.4, 28.5])

In [9]:
# 建立模型
regr = linear_model.LinearRegression()

# 訓練模型
regr.fit(x_train, y_train)

# 預測測試集
y_pred = regr.predict(x_test)

In [10]:
y_pred

array([11.46030778, 26.80269335, 17.43478925, 17.5563101 , 37.39156424,
       25.07675556, 31.05825852, 20.30845531, 19.66757374, 22.82655375,
       28.47083056, 28.53331605, 18.72883256, 33.11375161, 21.34282974,
       15.20554693, 21.57309275, 10.92841589, 11.69603405, 13.54311508,
        5.07126801, 17.40464043, 20.69379268, 22.72981238, 16.4634139 ,
       20.42666271, 17.53377349, 14.22644356, 21.56292745, 17.33136115,
       14.28888479, 23.92829804, 34.31523522, 22.03799035, 17.47895779,
       20.20386005, 30.70896335, 35.21599528, 24.07063567, 24.51445184,
       36.77425366, 33.15265201, 19.67545976, 31.93505104, 33.55222906,
       25.59147737, 40.59239607, 17.99555017, 19.92780188, 23.65319423,
       33.48950986])

In [11]:
# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Coefficients:  [-1.08149147  1.12829047  0.12616415  0.78282124 -2.00590875  2.53867624
  0.0616362  -3.14200313  2.78338743 -2.1432663  -2.00593495  0.86727598
 -3.80664956]
Mean squared error: 17.04
